server:
  port: 8047
spring:
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/spring-cloud?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    url: jdbc:mysql://localhost:3306/SpringCloud?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: create # 第一次建表create  后面用update
    show-sql: true

