
server:
  port: 8122

spring:
  application:
    name: admin-client
  ###没有集成注册中心时，需要配置admin server地址
#  boot:
#    admin:
#      client:
#        url: http://localhost:8888
  ###没有集成注册中心时，需要配置admin server地址

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8121}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart

###配置日志路径
logging:
  file: "logs/admin-client.log"

