spring:
  application:
    name: service-turbine
server:
  port: 8885
turbine:
  aggregator:
    clusterConfig: default
  appConfig: eureka-ribbon-client,eureka-feign-client
  clusterNameExpression: new String("default")
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8881/eureka/