server:
  port: 8042
management:
 # security:
   # enabled: false
    server:
      port: 9009
    endpoints:
      web:
        exposure:
         include: "*"
    endpoint:
      shutdown:
        enabled: true
