spring:
  application:
    name: eureka-ribbon-client

server:
  port: 8873

management:
  endpoints:
    web:
      exposure:
        #include: 'hystrix.stream'
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8871/eureka/
