spring:
  application:
    name: eureka-ribbon-client
server:
  port: 8883
management:
  endpoints:
    web:
      exposure:
        #include: 'hystrix.stream'
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8881/eureka/
