spring:
  application:
    name: eureka-feign-client
server:
  port: 8874

management:
  endpoints:
    web:
      exposure:
        #include: 'hystrix.stream'
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8871/eureka/

feign:
  hystrix:
    enabled: true

