server:
  port: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8111/eureka/

spring:
  application:
    name: gateway-service
  sleuth:
    sampler:
      probability: 1.0
#  zipkin:
#    base-url: http://localhost:9411

zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: user-service
